backend:
  name: git-gateway
  branch: master
  site_domain: cms.netlify.com
  repo: nikkieverett/research-and-development
local_backend: true
media_folder: static/img
media_library:
  name: cloudinary
  config:
    cloud_name: outdoorrnd
    api_key: 918386622724147
    multiple: true
public_folder: /img
collections:
  - name: "stops"
    label: "Stops"
    folder: "content/stops"
    editor: { preview: false }
    slug: "{{location}}"
    create: true
    path: "{{location}}/index"
    fields:
      - { label: "Location / Name", name: "location", widget: "string" }
      - label: "Daily Log"
        name: "dailyLog"
        widget: "list"
        fields:
          - { label: "Day # / Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "date", format: "MMM D YY" }
          - { label: "Content", name: "content", widget: "markdown" }
          - {
              label: "Cover Image",
              name: "coverImage",
              widget: "image",
              required: false,
            }
      - label: "Hiking"
        name: "hiking"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - { label: "Content", name: "content", widget: "markdown" }
          - {
              label: "Cover Image",
              name: "coverImage",
              widget: "image",
              required: false,
            }
      - label: "Golfing"
        name: "golfing"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - { label: "Content", name: "content", widget: "markdown" }
          - {
              label: "Cover Image",
              name: "coverImage",
              widget: "image",
              required: false,
            }
      - label: "Lodging"
        name: "lodging"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - { label: "Content", name: "content", widget: "markdown" }
          - {
              label: "Cover Image",
              name: "coverImage",
              widget: "image",
              required: false,
            }
      - label: "Dining"
        name: "dining"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - { label: "Content", name: "content", widget: "markdown" }
          - {
              label: "Cover Image",
              name: "coverImage",
              widget: "image",
              required: false,
            }
      - label: "Gallery"
        name: "galleryImages"
        widget: "image"
        allow_multiple: true
  - name: "trips"
    label: "Trips"
    folder: "content/trips"
    editor: { preview: false }
    slug: "{{title}}"
    create: true
    path: "{{title}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Start Date",
          name: "startDate",
          widget: "date",
          format: "MMM D YY",
        }
      - {
          label: "End Date",
          name: "endDate",
          widget: "date",
          format: "MMM D YY",
        }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Stops"
        name: "stops"
        widget: "list"
        summary: "{{fields.city}}, {{fields.state}}"
        fields:
          - { label: City, name: city, widget: string }
          - { label: State, name: state, widget: string }
          - {
              label: "Start Date",
              name: "startDate",
              widget: "date",
              format: "MMM D YY",
            }
          - {
              label: "End Date",
              name: "endDate",
              widget: "date",
              format: "MMM D YY",
            }
          - {
              laenl: "Cover Image",
              name: "coverImage",
              widget: "image",
              required: false,
            }
          - {
              label: Published,
              name: published,
              widget: boolean,
              required: false,
            }
  - name: "pages"
    label: "Pages"
    editor: { preview: false }
    files:
      - label: "Home"
        name: "home"
        file: "content/home/index.md"
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Current Location, name: currentLocation, widget: string }
          - {
              label: Current Location Map Image,
              name: currentMapImage,
              widget: image,
            }
          - label: Trip Details
            name: tripDetails
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Number, name: number, widget: string }
          - label: Gallery Images
            name: homeGalleryImages
            widget: image
            allow_multiple: true
